# -*- coding: utf-8 -*-
"""Python_class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LF3L89p7Cje4rUsC_7NAe1ZkB_tz_rhE
"""

def square(n):
    return n*n
    
a=square(3)
print(a)

def maximum(a,b):
    if a>=b:
        max=a
    else:
        max=b
    return max

maximum(4,3)

def 요금(무게):
    if 무게>=20:
        print("2만원")
    else:
        print("수수료 없음")
        
요금(35)

def 날짜출력(month,last):
    for day in range(1,last+1):
        print(month,day)
        
날짜출력(1,31)

"""Television 리모콘과 같은 기능을 만들어보자"""

class Television():
    def __init__(self, volume, power):
        self.volume=volume
        self.power=power
        
    def show(self):
        print(self.volume,self.power)
    
    def max(self):
        self.volume=100
        
    def min(self):
        self.volume=0
        
    def mute(self):
        self.volume='mute'
        
    def on(self):
        self.power=True
        
    def off(self):
        self.power=False

TV=Television(5,True)

TV.volume

TV.max()

TV.volume

TV.off()

TV.power

TV.show()

"""계산기"""

class Calculator:
    def __init__(self):
        self.value=0
        
    def add(self,number):
        self.value+=number
        
    def sub(self,number):
        self.value-=number
        
    def mul(self,number):
        self.value*=number
        
    def div(self,number):
        self.value/=number

C=Calculator()
C.add(3)
C.add(2)
C.sub(1)
C.mul(3)
C.div(6)
print(C.value)

"""끝말잇기"""

word1=input()
word_list=[]

for i in range(1,100):
    word2=input()
    
    if word1[-1]==word2[0]:
        print(word1,word2,"pass")
        word_list.append(word2)
        word1=word2
        
    elif word1[-1]!=word2[0]:
        print(word1,word2,"break")
        break
        
    elif word2 in word_list:
        print(word_list,word2,"break")
        break